### PR TITLE
added ability to add formatted markdown to a section of migradoc document

### PR DESCRIPTION
**Pull request by julianrendell**
Hi-

this allows the addition of Markdown to an existing migradoc doc.

The driver for this is a log analysis tool that I'm working on; internally it creates 'analysis notes' that are formated in Markdown; adding that with this change means I can generate a pdf document and iterate over all the notes analysis notes and add them to one pdf document.

I've just realised that this also will allow the inclusion of markdown into any document type that migradoc can export to.

### CODE REVIEW

**Comment by julianrendell** [comment]
Hi-

pull request now includes a small fix to be compatible with newer versions of FSharp.Formatting (HTMLBlock -> InlineBlock).

**Comment by theburningmonk** [comment]
Hello, thanks for doing this, we're busy with launching our game on iPad at the moment and I might not have a chance to look at this for a few more days yet, hope that's alright with you.

**Comment by theburningmonk** [comment]
Merged. Will publish updated Nuget package shortly.

**Comment by theburningmonk** [comment]
Nuget package pushed.

**Pull request merged**
